name: Annotate Git Diff
description: Shows git diff between current commit and target branch as a build annotation
author: github.com/mcncl
requirements:
  - git
configuration:
  properties:
    context:
      type: string
      default: "git-diff"
    format:
      type: string
      enum: ["markdown", "diff"]
      default: "markdown"
    compare_branch:
      type: string
      default: ""
    compare_commits:
      type: integer
      default: 1
      minimum: 1
    include_merge_base:
      type: boolean
      default: true
    include_submodules:
      type: boolean
      default: false
    compare_previous_build:
      type: boolean
      default: false
    buildkite_api_token:
      type: string
      default: ""
  additionalProperties: false
    
